language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
install:
- ". ./ci/install-swagger-codegen.sh"
- openssl aes-256-cbc -K $encrypted_fee8b359a955_key -iv $encrypted_fee8b359a955_iv -in ./ci/id_rsa.enc -out ./ci/id_rsa -d

script:
- "/bin/sh ./generate-sdks"
after_success:
- git config --global user.name "Travis CI"
- git config --global user.email "${TEAM_EMAIL}"
- "/bin/sh ./travis-ci/push-java-sdk.sh"
